In [1]:
import pandas as pd
import numpy as np
import nltk 
import string
import re
import os

In [2]:
#pemanggilan data mentah
data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/dataset_preprocessed.xlsx')

In [3]:
pos_sent = open("/content/drive/MyDrive/Colab Notebooks/kamus sentimen/positive.txt").read()
positive_words=pos_sent.split('\n')

In [4]:
neg_sent = open("/content/drive/MyDrive/Colab Notebooks/kamus sentimen/negative.txt").read()
negative_words=neg_sent.split('\n')

In [5]:
data['Facebook'] = [str(fb) for fb in data['Facebook']]

In [6]:
data['count'] = data['Facebook'].apply(lambda Facebook: sum(0 + ((word in positive_words) and 1) + ((word in negative_words) and -1) for word in Facebook.split()))

In [7]:
data['sentimen'] = 'netral'
data['sentimen'][data['count']>0] = 'positif'
data['sentimen'][data['count']<0] = 'negatif'
data['sentimen'][data['count']==0] = 'netral'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
data

                                               Facebook  count sentimen
0     yg udah nyoba kepingin nyoba yg nyoba sila mam...      0   netral
1                                promo ahir taun gk min      0   netral
2                                         psan promonyo      0   netral
3                                     lokasi dimna mbak      0   netral
4                       lw yg simpang blilas dimna mbak      0   netral
...                                                 ...    ...      ...
1215                                                mna      0   netral
1216                                             pandan      0   netral
1217                                        my favorite      0   netral
1218                                   dmna almt ny gan      0   netral
1219                     kk cabang dipekanbaru dimn aja      0   netral

[1220 rows x 3 columns]

In [ ]:
data.to_csv("data_baru.csv")