In [ ]:
from __future__ import print_function
from __future__ import division
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB 

import pandas as pd
import numpy as np
import re, string
import matplotlib.pyplot as plt
import math

In [ ]:
tel = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/data-label-baru.xlsx')

In [ ]:
tel

,Unnamed: 0,Facebook,count,sentimen
0,0,yg udah nyoba kepingin nyoba yg nyoba sila mam...,0,netral
1,1,promo ahir taun gk min,0,netral
2,2,psan promonyo,0,netral
3,3,lokasi dimna mbak,0,netral
4,4,lw yg simpang blilas dimna mbak,0,netral
...,...,...,...,...
1215,1215,mna,0,netral
1216,1216,pandan,0,netral
1217,1217,my favorite,0,netral
1218,1218,dmna almt ny gan,0,netral
1219,1219,kk cabang dipekanbaru dimn aja,0,netral

In [ ]:
tel['Facebook'] = [str(tw) for tw in tel['Facebook']]
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
tel[tel['sentimen'] =='positif'].shape
tel[tel['sentimen'] =='negatif'].shape

(65, 4)

In [ ]:
tel['Facebook'] = [str(tw) for tw in tel['Facebook']]
#vector = CountVectorizer()
vector_tf = TfidfVectorizer(max_df=0.9, min_df=0.02)
#matrix_kata =  vector.fit_transform(examp.stemming)
matrix_kata_tf = vector_tf.fit_transform(tel.Facebook)
matrix_kata_tf.shape

(1220, 30)

In [ ]:
data = pd.DataFrame(matrix_kata_tf.toarray(), columns=vector_tf.get_feature_names())
data

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aja,alhamdulillah,bakery,beli,berkah,brp,buka,cabang,enak,ga,...,pekanbaru,promo,roti,rotte,suka,sukses,toko,udah,ya,yg
0,0.000000,0.0,0.275978,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.425592,0.0,0.21423,0.0,0.0,0.0,0.402049,0.0,0.599612
1,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.626441,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000
2,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000
3,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000
4,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000
1216,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000
1217,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000
1218,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000
1219,0.592127,0.0,0.000000,0.0,0.0,0.0,0.0,0.561773,0.0,0.0,...,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.000000,0.0,0.000000

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(data, tel.sentimen, test_size=0.2, random_state=42)

print(y_test)

542     positif
259      netral
43       netral
1010     netral
754      netral
         ...
939      netral
243      netral
59       netral
1075     netral
63       netral
Name: sentimen, Length: 244, dtype: object

In [ ]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)

MultinomialNB()

In [ ]:
y_test_pred=clf.predict(X_test)
confusion_matrix(y_test,y_test_pred)
skor_prediksi = clf.predict_proba(X_test)
hasil_prediksi = clf.predict(X_test)
print(classification_report(y_test,y_test_pred))
clf.score(X_test,y_test)
print(confusion_matrix(y_test,y_test_pred))

              precision    recall  f1-score   support

     negatif       0.00      0.00      0.00         9
      netral       0.87      1.00      0.93       200
     positif       1.00      0.40      0.57        35

    accuracy                           0.88       244
   macro avg       0.62      0.47      0.50       244
weighted avg       0.86      0.88      0.84       244

[[  0   9   0]
 [  0 200   0]
 [  0  21  14]]

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
print(hasil_prediksi)

['positif' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'positif' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'positif' 'positif' 'netral'
 'positif' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'positif' 'positif' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'positif' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'positif'
 'netral' 'netral' 'netral' 'netral' 'netral' 'positif' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'positif' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'positif' 'positif' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'positif' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral' 'netral'
 'netral' 'netral' 'netral' 'netral']

In [ ]:
ss = pd.DataFrame(skor_prediksi, columns=['negatif','positif','netral'])

In [ ]:
ss

      negatif   positif    netral
0    0.030827  0.292010  0.677163
1    0.057377  0.768443  0.174180
2    0.082687  0.799399  0.117913
3    0.057377  0.768443  0.174180
4    0.057377  0.768443  0.174180
..        ...       ...       ...
239  0.045409  0.916362  0.038229
240  0.057377  0.768443  0.174180
241  0.057377  0.768443  0.174180
242  0.039817  0.865486  0.094697
243  0.045677  0.889362  0.064960

[244 rows x 3 columns]